### ISSUE TITLE
Change repo structure so it can be installed with hacs

### ISSUE THREAD

**Issue by Kraechtshammer** [zomfg/home-assistant-prismatik#10]
Hi,
first of all thanks for the great integration, works great for me!
I installed the integration manually for now but it would be great if you could change the repo structure so it can be installed using hacs (home assistant community store). There really is not much to do except for some change in folder structure I think, but then we could easily auto install it and also auto-update using hacs. Here is the list of repos so you may look into the structure it takes: https://hacs.xyz/docs/default_repositories 
An option would be even to add this to the default hacs repos: https://hacs.xyz/docs/publish/start

**Comment by zomfg** [comment]
Hi, thanks!
try adding the repo to HACS now

**Comment by Kraechtshammer** [comment]
Oops forgot to answer, thanks a lot for the quick reaction, it works great now and I'm using the Integration more than I expected I would, great work!
