### ISSUE TITLE
Color change times out after 60 seconds

### ISSUE THREAD

**Issue by Hukuma1** [zomfg/home-assistant-prismatik#13]
Awesome integration. Thank you for this!

When I change a color in HA it stays on my screen for 60 seconds and then the LEDs go dark.

<img width="291" alt="prismatikha" src="https://user-images.githubusercontent.com/54511555/147839154-be698ef3-7211-43f6-a17e-1081bbda3f46.png">

The profile is still saying `hass` so it's still locked, etc. I can manually switch it to my desktop one (`Adalight`) to re-gain my Screen Grabbing, or I can manually choose a color again in HA to re-engage the color. But basically it seems to turn off after 60 seconds.

Not sure if this is a bug, or a setting I can turn off? Or if a keep alive feature could be added?

**Comment by zomfg** [comment]
Hi
some adalight sketches have a timeout built in, so you could disable that, or in Prismatik > Expert tab,  try flipping "Send data only if colors changed" checkbox

**Comment by Hukuma1** [comment]
Hmmm. I see, so I actually like the time out feature from the sketch to stay on for my screen grab function (if I'm away from my computer, it turns off, great). 

But for specific colors or commands sent from HA, I'd like to leave it on. At which point I could also automate to turn off within HA.

I already have the "send data only if colors changed" turned on. I tried the same with it off and HA color would still turn off after the timeout (60 in my sketch I believe). (It stayed on with screen grabbing, even past my time out. But in HA it would turn off no matter what setting was in Prismatik.)

**Comment by zomfg** [comment]
which Prismatik version are you using?

**Comment by Hukuma1** [comment]
software 5.11.2.30 (rev 25c8dfe, Qt 5.15.2)

**Comment by zomfg** [comment]
imo, unchecking that box is what you want for your use case, but make sure you do it with HA profiles (in Prismatik) as it's tied to them
so maybe when you tested, you did it with your pc profile and when HA took over it enabled the checkbox again

**Comment by Hukuma1** [comment]
Oh I see, brilliant. I wasn't aware that was a per-profile setting.

So the weird thing is that it works if I switch the color in Prismatik. Mood lamp profile with custom color. Goes past the 60 second time out and still on.

If I still try to change the color via HA, it times out. :/

**Comment by zomfg** [comment]
ha.. it looks like Prismatik does not work the same way depending on how you set modes/colors:
* via UI it'll continue sending frames
* via API (what HA uses) it stops everything once it gets some commands

so for now, changing your sketch is the next best thing

**Comment by Hukuma1** [comment]
Ahh. Well now we know. :) I guess I could put in a simple keep-alive method in HA by just spamming the same color change for now.
