### ISSUE TITLE
Привет не знаю как еще связаться

### ISSUE THREAD

**Issue by inhuman** [zomfg/home-assistant-prismatik#15]
Привет не знаю как еще связаться) Я видел в репе [по яндекс станции](https://github.com/AlexxIT/YandexStation) твое ишью касательно кондиционера daichi, там ты написал что добавил его в HA
Как ты его добавлял?) 
можешь на почту ответить? msgexe@gmail.com

**Comment by zomfg** [comment]
wrong person, good luck on your quest tho
