### ISSUE TITLE
Changing brightness sets api colors persisted

### ISSUE THREAD

**Issue by christoros** [zomfg/home-assistant-prismatik#17]
Is there any way for prismatik to keep on screen grabbing after changing the brightness in home assistant. Personally I don't have any interest in setting my backlight in a single color. I just want to be able to adjust the brightness of my backlight with HA. Currently prismatik locks up after changing the brightness and it won't continue screen grabbing until switching from profile. Is there any way for prismatik to keep on screen grabbing after changing the brightness?

**Comment by zomfg** [comment]
not the way your are trying to do it with a slider, I assume (not in current state of things anyway)
but.. you could make multiple profiles with grabbing mode + brightness level you want and switch between those in HA ("effects" list)
