### ISSUE TITLE
Deprecated features - Will be removed in HA 2025.1

### ISSUE THREAD

**Issue by FaserF** [zomfg/home-assistant-prismatik#18]
Entity None (<class 'custom_components.prismatik.light.PrismatikLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature.EFFECT|17: 21> and color modes, please report it to the author of the 'prismatik' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by zomfg** [comment]
hi! thanks, try the update
we traded it for 
```
None (<class 'custom_components.prismatik.light.PrismatikLight'>) sets invalid supported color modes {<ColorMode.BRIGHTNESS: 'brightness'>, <ColorMode.HS: 'hs'>}, this will stop working in Home Assistant Core 2025.3, please report it to the author of the 'prismatik' custom integration
```
and gained few months, yay!
