### ISSUE TITLE
WebSocket Error

### ISSUE THREAD

**Issue by camcs1** [zomfg/home-assistant-prismatik#4]
### Bug Description 
When I turn on the prismatik using the home assistant UI I get the following error: 
> Failed to call service light/turn_on. 'NoneType' object is not subscriptable 
 Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 125, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1265, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1300, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 471, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 277, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 316, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 426, in state_attributes
    data[ATTR_HS_COLOR] = (round(hs_color[0], 3), round(hs_color[1], 3))
TypeError: 'NoneType' object is not subscriptable

The lightpack turns on normally and the state in home assistant briefly changes to on, then reverts to off. If I then try to turn the lightpack on/off I get the following error: 
> Could not lock prismatik

If I am persistent in mashing the button it will eventually turn off and the bug will reoccur

### Enviroment Description 
Home Assistant 0.113.1
Prismatik Version 5.11.2.23
WLED version 0.10.0 (Configured as UDP DRGB in prismatik) 
Windows 10 1909

Thank's for all your work on Prismatik and this component for Home Assitant ❤️

**Comment by zomfg** [comment]
Hmmm it's seems fine on 0.113.3 for me, and I think it was also fine on 0.113.0, so not sure what's going on, try upgrading HA if you can
I know I did not implement all of the async stuff (yet), but it haven't caused issues in my tests and there are multiple builtin light integrations that don't have async stuff either:
```sh
$ find . -name 'light.py' -exec grep -LH async {} \;
./avea/light.py
./zengge/light.py
./decora/light.py
./lifx_legacy/light.py
./mochad/light.py
./unifiled/light.py
./enocean/light.py
./opple/light.py
./sensehat/light.py
./piglow/light.py
./iglo/light.py
./tikteck/light.py
./scsgate/light.py
./hive/light.py
./futurenow/light.py
./nanoleaf/light.py
./skybell/light.py
./blinkt/light.py
./avion/light.py
./pilight/light.py
./decora_wifi/light.py
./lutron/light.py
./x10/light.py
./osramlightify/light.py
./tellstick/light.py
./lw12wifi/light.py
./flux_led/light.py
./xbee/light.py
./greenwave/light.py
./homematic/light.py
./litejet/light.py
./yeelightsunflower/light.py
./hyperion/light.py
./blinksticklight/light.py
./eufy/light.py
```
Do you use some kind of light/async related setting in your HA?

**Comment by camcs1** [comment]
Thanks for your prompt response, I have updated HA to 0.113.3 and the issue persists. 

I've done some testing with a virtual LED device set to static red and noticed this bug only seems to occur when using 200 or more LEDS (tested: 1, 2, 20, 50, 100 & 150 with no issue)

To expand on the behaviour of the bug I am sometimes (usually after a Home Assitant restart) able to turn the lights on and off once, before the bug occurs. 

Also when skimming similar issues and the HA doc's I think the nonetype error is due to a problem with ATTR_HS_COLOR. 

I am using a few other light components (WLED & esp8266_milight_hub) however this is my only light custom component and I've not customised any light or async related setting. 

Also to expand my environment description I am running HassOS 4.11 on a Raspberry Pi

**Comment by zomfg** [comment]
try enabling debug logs in `configuration.yaml`
```yaml
logger:
  default: warning
  logs:
    custom_components.prismatik: debug
```

**Comment by zomfg** [comment]
and try this [light.py](https://github.com/zomfg/home-assistant-prismatik/blob/feature/test-update/light.py)
edit: updated

**Comment by camcs1** [comment]
Second light.py has fixed it, the environment as described in the OP now works perfectly. 

Thank you again for creating this component and responding so diligently to my issue 👍 

If you still want me to try with the custom logging I'm more than happy to. 

I've only had a chance to play with this again today, sorry for the delay in getting back to you.

**Comment by zomfg** [comment]
Oh cool!
yeah I think I understood what was wrong so the logs won't add much here probably (unless you have new related issues)
thanks for the feedback 👍
