### ISSUE TITLE
Feature request - Profiles

### ISSUE THREAD

**Issue by nirkons** [zomfg/home-assistant-prismatik#6]
Hi,

I was wondering if it was possible to be able to get the list of profiles from prismatik and be able to change it in homeassistant.

thanks!

**Comment by camcs1** [comment]
This is already supported, check the state attributes in developer tools. 

They are presented as effects due to a limitation on how Home Assistant handles light entities. 


I recommend the [custom light entity card](https://github.com/ljmerza/light-entity-card) if you want to quickly switch between profiles

**Comment by nirkons** [comment]
Thanks for the quick reply, I'll check out the custom light card,
but just btw this is the built in Hyperion integration with an effects list, maybe that could be used to display the profiles instead of the workaround

![image](https://user-images.githubusercontent.com/24681877/93348917-7eab3900-f83f-11ea-82d1-461a0896d74f.png)

**Comment by camcs1** [comment]
Prismatik has the same thing, the custom light card is just advantageous as you don't have to go into the pop out view 

**Default light card pop out**
![image](https://user-images.githubusercontent.com/27576381/93349320-3d129200-f82f-11ea-9b6b-81f70052cdea.png)
**Custom Light Card (No popout)** 
![image](https://user-images.githubusercontent.com/27576381/93349569-895dd200-f82f-11ea-966d-4e2ccf46af18.png)

**Comment by nirkons** [comment]
That was so strange, I only had the brightness setting and thats it.
Now after restarting the entire NUC the effect list appeared with my profiles, might be a bug I guess? sorry for the confusion.

thanks!
